### PR TITLE
Fix incorrect requests size in QuicHandleRpsClient

### PR DESCRIPTION
**Pull request by thhous-msft**
Fixes regression from #2110

### CODE REVIEW

**Review by csujedihy — APPROVED** [review]

**Review by nibanks — APPROVED** [review]

**Comment by csujedihy** [comment]
I've hit a warning when I built it locally.

**Comment by nibanks** [comment]
@thhous-msft :
```
D:\a\1\msquic\src\perf\bin\appmain.cpp(49,23): error C2220: the following warning is treated as an error [D:\a\1\msquic\build\windows\x64_schannel\src\perf\bin\secnetperf.vcxproj]
D:\a\1\msquic\src\perf\bin\appmain.cpp(49,23): warning C4244: 'initializing': conversion from 'uint64_t' to 'uint32_t', possible loss of data [D:\a\1\msquic\build\windows\x64_schannel\src\perf\bin\secnetperf.vcxproj]
```

**Review by csujedihy — CHANGES_REQUESTED** [review]
uint32_t MaxCount = CXPLAT_MIN(CachedCompletedRequests, RestOfBufferLength);
->
uint32_t MaxCount = CXPLAT_MIN((uint32_t )CachedCompletedRequests, RestOfBufferLength);

**Review by csujedihy — APPROVED** [review]
