### ISSUE TITLE
VS2019 16.7.0 build failure

### ISSUE THREAD

**Issue by moso1** [microsoft/msquic#704]
I encounter new problem building msquic.kernel.sln possibly after I upgrade VS2019 to 16.7.0.

msquic\src\platform\datapath_winkernel.c(2202): error C6011: Dereferencing NULL pointer 'Binding'. 
msquic\src\platform\hashtable.c(731): error C6387: 'ContextPtr->ChainHead' could be '0':  this does not adhere to the specification for the function 'QuicListIsEmpty'.
