### PR TITLE
gamecore_console: default to latest Windows SDK

### PR DESCRIPTION
**Pull request by jianye-chen**
## Description

This is the follow-up PR to [#3332](https://github.com/microsoft/msquic/pull/3332).  
We hard coded `CMAKE_SYSTEM_VERSION` to `10.0.18362.0`, which also applied to our `gamecore_console` releases. According to [Windows 10 Software Development Kit (Win10SDK)](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/getstarted/overviews/sdk-and-tools#windows-10-software-development-kit-win10sdk), `WINAPI_FAMILY_GAMES` is only usable on or after `Windows 10 SDK version 19041 or later`. 

In `10.0.18362.0`, `winapifamily.h` mistakenly categories `WINAPI_FAMILY_GAMES` under `WINAPI_PARTITION_SYSTEM`,
```cpp
/*
 * The mapping between families and partitions is summarized here.
 * An X indicates that the given partition is active for the given
 * platform/family.
 *
 *                                +---------------------------+
 *                                |      *Partition*          |
 *                                +---+---+---+---+---+---+---+
 *                                |   |   |   |   |   |   |   |
 *                                |   |   |   |   |   |   |   |
 *                                |   |   |   | P |   |   |   |
 *                                |   |   |   | H |   |   |   |
 *                                | D |   |   | O |   |   |   |
 *                                | E |   | P | N | S | S |   |
 *                                | S |   | C | E | Y | E | G |
 *                                | K |   | _ | _ | S | R | A |
 *                                | T | A | A | A | T | V | M |
 * +-------------------------+----+ O | P | P | P | E | E | E |
 * |     *Platform/Family*       \| P | P | P | P | M | R | S |
 * +------------------------------+---+---+---+---+---+---+---+
 * | WINAPI_FAMILY_DESKTOP_APP    | X | X | X |   |   |   |   |
 * +------------------------------+---+---+---+---+---+---+---+
 * |      WINAPI_FAMILY_PC_APP    |   | X | X |   |   |   |   |
 * +------------------------------+---+---+---+---+---+---+---+
 * |   WINAPI_FAMILY_PHONE_APP    |   | X |   | X |   |   |   |
 * +----------------------------- +---+---+---+---+---+---+---+
 * |      WINAPI_FAMILY_SYSTEM    |   |   |   |   | X |   |   |
 * +----------------------------- +---+---+---+---+---+---+---+
 * |      WINAPI_FAMILY_SERVER    |   |   |   |   | X | X |   |
 * +------------------------------+---+---+---+---+---+---+---+
 * |       WINAPI_FAMILY_GAMES    |   |   |   |   |   |   | X |
 * +------------------------------+---+---+---+---+---+---+---+
 *
 * The table above is encoded in the following expressions,
 * each of which evaluates to 1 or 0.
 *
 * Whenever a new family is added, all of these expressions
 * need to be reconsidered.
 */

...

#ifndef WINAPI_PARTITION_SYSTEM
#define WINAPI_PARTITION_SYSTEM                                                \
  (WINAPI_FAMILY == WINAPI_FAMILY_SYSTEM ||                                    \
   WINAPI_FAMILY == WINAPI_FAMILY_GAMES ||                                     \
   WINAPI_FAMILY == WINAPI_FAMILY_SERVER)
#endif 
```

This bypasses the guard in `timeapi.h` as `WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)` now evaluates to `true`, thus polling in unavailable symbols on `gamecore_console` (as `#ifdef TIMERR_NOERROR` won't save us anymore).  
  
In `10.0.19041.0`, `WINAPI_PARTITION_SYSTEM` no longer includes `WINAPI_FAMILY_GAMES` and therefore hides `timeapi.h`'s definitions correctly.
```cpp
#ifndef WINAPI_PARTITION_SYSTEM
#define WINAPI_PARTITION_SYSTEM                                                \
  (WINAPI_FAMILY == WINAPI_FAMILY_SYSTEM ||                                    \
   WINAPI_FAMILY == WINAPI_FAMILY_SERVER)
#endif 
```
  
In this PR, we will,
1. revert the temporary fix in [#3332](https://github.com/microsoft/msquic/pull/3332)
2. avoid setting a default Windows SDK version in our build script; `uwp` system name needs to be `10.0` instead of `10`
3. verify the selected Windows SDK is on or after version `10.0.19041.0` for gamecore_console builds
4. avoid linking to `onecore` on `uwp` and `gamecore_console`, replace most windows rt linkages with `onecore`

## Testing

No tests needed.  
In the future, attempting to reference a symbol not available on the targeted win32 platform will result in a compile error.  

## Documentation

N/A

### CODE REVIEW

**Comment by nibanks** [comment]
Looks like this caused a TON of new warnings and errors to pop up.

https://dev.azure.com/ms/msquic/_build/results?buildId=415905&view=logs&j=d4d09c0a-def6-5725-48a6-b95bba6d3796&t=440d8ed1-77a3-589e-4856-1a38dac960f9

Errors for schannel are because we're using too old of SDK I think.

**Comment by jianye-chen** [comment]
Our ado pipelines are running on `windows-2019` which is `10.0.17763`. By default, CMake selects the matching SDK for the exact system version if we don't override it ([cmGlobalVisualStudio14Generator.cxx#L363](https://github.com/Kitware/CMake/blob/d340fcdbb7c25e51343d3502bf4e971407f74f0d/Source/cmGlobalVisualStudio14Generator.cxx#L363)).  
  
Previously we pinned our builds to SDK `10.0.18362.0`. Strictly speaking, the produced binaries won't run appropriately on `windows-2019` because we would have to specify [Target Platform Min. Version](https://learn.microsoft.com/en-us/cpp/build/reference/general-property-page-project?view=msvc-170#target-platform-min-version) and [check the version of the platform it's running against at runtime and disable features that aren't available in older platform versions](https://learn.microsoft.com/en-us/cpp/build/reference/general-property-page-project?view=msvc-170#target-platform-version).  

What's the minimum Windows platform we intend to support? Windows 10 LTSC 2019's mainstream support ends on `Jan 9, 2024`, and supporting that means we need to support platform `10.0.17763` (as ltsc 2019 is based off 1809).  

I will modify this PR to specify the latest SDK when building for `gamecore_console` only (similar to what we are doing for `uwp` right now).

**Comment by nibanks** [comment]
When building for Schannel (the inbox Windows TLS library) we probably need to stay with `10.0.18362.0`. If we use OpenSSL, we probably don't have any minimum.

**Comment by jianye-chen** [comment]
Probably also means we shouldn't do the umbrella library changes. Some critical issues were also resolved since SDK `10.0.19041.0`: [Resolved unpredictable and hard to diagnose crashes when linking both umbrella libraries and native OS libraries](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/).  
  
Reworked this PR to use the latest SDK when building for gamecore_console.

**Review by nibanks — APPROVED** [review]

**Comment by nibanks** [comment]
@jianye-chen this seems to have broken our [internal build pipeline](https://mscodehub.visualstudio.com/msquic/_build/results?buildId=326302&view=logs&j=9eb7dcd7-eded-5639-f747-a9e47b733ee9&t=568989fa-4a2f-590f-4aaf-bc02cd690a4f&l=340).

The previous build that worked seemed to use:
```
-- System name: Windows
-- System version: 10.0.18362.0
-- Platform version: 10.0.18362.0
```

And the failed build now uses:
```
-- System name: Windows
-- System version: 10.0
-- Platform version: 10.0.19041.0
```

Some of the errors:
```
C:\__w\1\s\src\inc\quic_platform_winuser.h(1127,32): warning C4013: 'SetThreadIdealProcessor' undefined; assuming extern returning int (compiling source file C:\__w\1\s\src\core\api.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\core\core.vcxproj]
C:\__w\1\s\src\platform\platform_winuser.c(632,37): warning C4013: 'GetLogicalProcessorInformationEx' undefined; assuming extern returning int [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(423,5): error C2061: syntax error: identifier 'UNICODE_STRING' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(425,25): error C2061: syntax error: identifier 'rgstrChainingModes' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(425,25): error C2059: syntax error: ';' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(428,1): error C2059: syntax error: '}' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(433,5): error C2061: syntax error: identifier 'PUNICODE_STRING' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(436,25): error C2061: syntax error: identifier 'pDisabledCrypto' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(436,25): error C2059: syntax error: ';' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(438,1): error C2059: syntax error: '}' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(457,5): error C2061: syntax error: identifier 'PTLS_PARAMETERS' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\schannel.h(458,1): error C2059: syntax error: '}' (compiling source file C:\__w\1\s\src\platform\tls_schannel.c) [C:\__w\1\s\build\gamecore_console\x64_schannel\src\platform\platform.vcxproj]
...
```

Please let me know ASAP if you can't fix this soon, otherwise I will have to revert this. Thanks!

**Comment by jianye-chen** [comment]
`10.0.19041.0` SDK did not expose `SetThreadIdealProcessor` for `WINAPI_PARTITION_GAMES`,
```cpp
#pragma region Desktop Family or OneCore Family
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINBASEAPI
DWORD
WINAPI
SetThreadIdealProcessor(
    _In_ HANDLE hThread,
    _In_ DWORD dwIdealProcessor
    );


#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */
#pragma endregion
```
Could we bump the internal pipeline to a later SDK version?

**Comment by jianye-chen** [comment]
Tried a few SDKs. Tested `10.0.22000.0` and `10.0.22621.0` and they work.  

`10.0.20348.0` has a problem introduced from a previous bug fix:
```cpp
#if (defined(QUIC_GAMECORE_BUILD))
#include <sdkddkver.h>
#ifdef NTDDI_WIN10_CO
typedef struct _UNICODE_STRING {
    USHORT Length;
    USHORT MaximumLength;
    PWSTR Buffer;
} UNICODE_STRING, *PUNICODE_STRING;
#endif
#endif
```
Previously, we added the `UNICODE_STRING` definition for `NTDDI_WIN10_CO` or after because in versions before that we will see the abovementioned bug. I will do a separate PR to fix builds with `10.0.20348.0`.  
  
Build-wise, we still need to update to SDK >= `10.0.20348.0`. I will raise a separate PR to fix builds with `10.0.20348.0` by removing the `#ifdef NTDDI_WIN10_CO` in this block (as `WINAPI_PARTITION_GAMES` never provided a `UNICODE_STRING`).
